# Generated by Django 3.2.8 on 2021-10-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211028_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes_ratio', '-votes_total', 'title']},
        ),
    ]
